import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { unzipSync, zipSync, strFromU8, strToU8 } from 'fflate'
import { mkdir, writeFile } from 'node:fs/promises'
import type { CatalogPackage } from '../src/domain/models'
import { assertNoOverflow, assertCatalogImageRatio, assertVisibleImages, loadFullPageImages, readBrowserState, switchActor } from './browser-helpers'

const seed = JSON.parse(readFileSync('public/catalog.json', 'utf8')) as CatalogPackage
const published = seed.listings.filter(item => item.status === 'published')
const first = published[0]!

async function open(page: Page, route = '/') {
  await page.goto(`#${route}`)
  await expect(page.getByLabel('Текущий демо-участник', { exact: true })).toBeVisible()
}

function collectErrors(page: Page) {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  return errors
}

test('каталог содержит 48 вещей; прямая карточка переживает обновление на base path', async ({ page }) => {
  const errors = collectErrors(page)
  await open(page)
  await expect(page.getByTestId('listing-card')).toHaveCount(48)
  await expect(page.getByText('Демонстрационная версия. Вещи, цены и участники вымышлены. Изменения сохраняются только в этом браузере', { exact: true })).toBeVisible()
  await open(page, `/items/${first.slug}`)
  await expect(page.getByRole('heading', { name: first.title, exact: true })).toBeVisible()
  await assertVisibleImages(page)
  await page.reload()
  await expect(page.getByRole('heading', { name: first.title, exact: true })).toBeVisible()
  expect(new URL(page.url()).pathname).toBe('/chatgptrental20250809/')
  await assertVisibleImages(page)
  expect(errors).toEqual([])
})

test('адаптивность, первый экран, ресурсы и 12 контрольных снимков', async ({ page }, testInfo) => {
  test.setTimeout(180000)
  const errors = collectErrors(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await open(page)
  await assertVisibleImages(page)
  const firstImage = await page.getByTestId('listing-card').first().locator('img').boundingBox()
  expect(firstImage, 'В первом мобильном экране должна начинаться фотография').not.toBeNull()
  expect(firstImage!.y).toBeLessThan(844)
  const resources = await page.evaluate(() => {
    const entries = performance.getEntries().filter((entry): entry is PerformanceResourceTiming => entry.entryType === 'resource' || entry.entryType === 'navigation')
    return {
      viewport: { width: window.innerWidth, height: window.innerHeight },
      transferBytes: entries.reduce((sum, entry) => sum + (entry.transferSize || 0), 0),
      encodedBodyBytes: entries.reduce((sum, entry) => sum + (entry.encodedBodySize || 0), 0),
      resources: entries.map(entry => ({ path: new URL(entry.name).pathname, transferBytes: entry.transferSize, encodedBodyBytes: entry.encodedBodySize })),
    }
  })
  await mkdir('docs/screenshots', { recursive: true })
  await writeFile('docs/screenshots/mobile-first-load.json', JSON.stringify(resources, null, 2) + '\n')
  await testInfo.attach('mobile-first-load', { body: JSON.stringify(resources, null, 2), contentType: 'application/json' })
  for (const width of [360, 390, 768, 1024, 1440, 390]) {
    await page.setViewportSize({ width, height: width >= 1024 ? 1000 : 844 })
    await assertNoOverflow(page)
    await assertVisibleImages(page)
  }
  await switchActor(page, 'participant')
  await open(page, `/items/${first.slug}`)
  await page.getByRole('button', { name: 'Добавить в подборку', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).selections.find(item => item.actorId === 'participant')?.lines.length).toBe(1)
  const otherOwnerItem = published.find(item => item.ownerId !== first.ownerId)!
  await addItem(page, otherOwnerItem)
  await open(page, '/selection')
  await page.getByLabel('Первый день', { exact: true }).fill('2026-10-01')
  await page.getByLabel('Последний день', { exact: true }).fill('2026-10-03')
  await page.getByRole('heading', { name: 'Даты и расчёт', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).selections.find(item => item.actorId === 'participant')?.endDate).toBe('2026-10-03')
  if (await page.getByRole('button', { name: 'Закрыть сообщение', exact: true }).count()) await page.getByRole('button', { name: 'Закрыть сообщение', exact: true }).click()
  for (const width of [390, 1440]) {
    await page.setViewportSize({ width, height: width === 390 ? 844 : 1000 })
    const variant = width === 390 ? 'mobile' : 'desktop'
    const screens = [
      { name: 'catalog', route: '/', actor: 'participant' },
      { name: 'item', route: `/items/${first.slug}`, actor: 'participant' },
      { name: 'selection', route: '/selection', actor: 'participant' },
      { name: 'owner-account', route: '/account/listings', actor: first.ownerId },
      { name: 'listing', route: '/listing/new', actor: first.ownerId },
      { name: 'admin', route: '/admin/overview', actor: 'admin' },
    ]
    for (const screen of screens) {
      await switchActor(page, screen.actor)
      await open(page, screen.route)
      await assertNoOverflow(page)
      await loadFullPageImages(page)
      await assertCatalogImageRatio(page)
      await page.screenshot({ path: `docs/screenshots/${screen.name}-${variant}.png`, fullPage: screen.name !== 'catalog', animations: 'disabled' })
    }
  }
  expect(errors).toEqual([])
})

test('поиск, фильтры, сортировка, сброс и история URL', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await open(page)
  const target = published.find(item => /пл[её]ночный/i.test(item.title)) || first
  const query = target.title.toLocaleUpperCase('ru').replaceAll('Ё', 'Е')
  await page.getByLabel('Поиск реквизита', { exact: true }).fill(query)
  await page.getByRole('button', { name: 'Найти', exact: true }).click()
  await expect(page.getByTestId('listing-card')).toHaveCount(1)
  await expect(page.getByTestId('listing-card')).toHaveAttribute('data-id', target.id)
  expect(new URLSearchParams(page.url().split('?')[1]).get('q')).toBe(query)
  const category = seed.categories[0]!
  await page.getByRole('navigation', { name: 'Категории' }).getByRole('link').filter({ hasText: category.name }).click()
  await expect(page.getByTestId('listing-card')).toHaveCount(6)
  await page.goBack()
  await expect(page.getByLabel('Поиск реквизита', { exact: true })).toHaveValue(query)
  await expect(page.getByTestId('listing-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Убрать фильтр Поиск', exact: true }).click()
  await expect(page.getByTestId('listing-card')).toHaveCount(48)
  const owner = seed.sellers[0]!
  await page.getByRole('complementary', { name: 'Фильтры каталога' }).getByRole('combobox', { name: 'Владелец', exact: true }).selectOption(owner.userId)
  await expect(page.getByTestId('listing-card')).toHaveCount(published.filter(item => item.ownerId === owner.userId).length)
  await page.getByLabel('Сортировка', { exact: true }).selectOption('price-desc')
  const sortedIds = await page.getByTestId('listing-card').evaluateAll(cards => cards.map(card => card.getAttribute('data-id')))
  const prices = sortedIds.map(id => published.find(item => item.id === id)!.priceKopecks)
  expect(prices).toEqual([...prices].sort((a, b) => b - a))
  await page.getByRole('link', { name: 'Сбросить всё', exact: true }).first().click()
  await expect(page.getByTestId('listing-card')).toHaveCount(48)
  await page.getByLabel('Поиск реквизита').fill('Не существующий в каталоге предмет абракадабра')
  await page.getByRole('button', { name: 'Найти', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Вещи не найдены', exact: true })).toBeVisible()
  await expect(page.getByTestId('listing-card')).toHaveCount(0)
})

test('мобильные фильтры применяются явно, Escape возвращает фокус', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await open(page)
  const trigger = page.getByRole('button', { name: 'Фильтры', exact: true })
  await trigger.click()
  const modal = page.getByRole('dialog', { name: 'Фильтры каталога' })
  await modal.getByLabel('Цена до', { exact: true }).fill('1')
  await modal.getByRole('heading', { name: 'Фильтры каталога', exact: true }).click()
  await expect(modal).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(modal).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(page.getByTestId('listing-card')).toHaveCount(48)
  await trigger.click()
  await modal.getByLabel('Цена до', { exact: true }).fill('1')
  await modal.getByRole('button', { name: 'Применить', exact: true }).click()
  await expect(page.getByTestId('listing-card')).toHaveCount(0)
  await trigger.click()
  await modal.getByRole('button', { name: 'Сбросить', exact: true }).click()
  await modal.getByRole('button', { name: 'Применить', exact: true }).click()
  await expect(page.getByTestId('listing-card')).toHaveCount(48)
})

test('избранное сохраняется после reload и разделено между участниками', async ({ page }) => {
  await open(page)
  await switchActor(page, 'participant')
  const favorite = page.getByRole('button', { name: `В избранное: ${first.title}`, exact: true })
  await favorite.click()
  await expect(favorite).toHaveAttribute('aria-pressed', 'true')
  expect(new URL(page.url()).hash).toBe('#/')
  await page.reload()
  await expect(favorite).toHaveAttribute('aria-pressed', 'true')
  await open(page, '/favorites')
  await expect(page.getByTestId('listing-card')).toHaveCount(1)
  await switchActor(page, 'owner-8')
  await expect(page.getByTestId('listing-card')).toHaveCount(0)
  await switchActor(page, 'participant')
  await expect(page.getByTestId('listing-card')).toHaveCount(1)
  const state = await readBrowserState(page)
  expect(state.favorites).toEqual([{ actorId: 'participant', listingId: first.id }])
})

test('одновременные изменения в двух вкладках не теряют избранное', async ({ page, context }) => {
  await open(page)
  await switchActor(page, 'participant')
  const other = await context.newPage()
  await open(other)
  await switchActor(other, 'participant')
  const second = published.find(item => item.id !== first.id)!
  await Promise.all([
    page.getByRole('button', { name: `В избранное: ${first.title}`, exact: true }).click(),
    other.getByRole('button', { name: `В избранное: ${second.title}`, exact: true }).click(),
  ])
  await expect.poll(async () => (await readBrowserState(page)).favorites.filter(item => item.actorId === 'participant').length).toBe(2)
  await expect(page.getByRole('button', { name: `В избранное: ${second.title}`, exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(other.getByRole('button', { name: `В избранное: ${first.title}`, exact: true })).toHaveAttribute('aria-pressed', 'true')
  await other.close()
})

async function addItem(page: Page, item: typeof first, quantity = 1) {
  await open(page, `/items/${item.slug}`)
  await page.getByLabel('Количество предметов', { exact: true }).fill(String(quantity))
  await page.getByRole('button', { name: 'Добавить в подборку', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Вещь добавлена в подборку')
}
const formatMoney = (kopecks: number) => new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB', maximumFractionDigits: kopecks % 100 ? 2 : 0 }).format(kopecks / 100)

test('подборка двух владельцев: 1 и 3 дня, количество, залог, ошибки и сохранение при входе', async ({ page }) => {
  const many = published.find(item => item.quantity >= 2)!
  const another = published.find(item => item.ownerId !== many.ownerId)!
  await open(page, '/selection')
  await expect(page.getByRole('heading', { name: 'Здесь начинается новая история' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Отправить демо-запрос', exact: true })).toHaveCount(0)
  await addItem(page, many)
  await addItem(page, another)
  await open(page, '/selection')
  await expect(page.getByTestId('selection-line')).toHaveCount(2)
  await page.getByLabel('Первый день', { exact: true }).fill('2026-10-03')
  await page.getByLabel('Последний день', { exact: true }).fill('2026-10-01')
  await expect(page.getByRole('alert')).toContainText('Окончание не может быть раньше начала')
  expect((await readBrowserState(page)).requestGroups).toHaveLength(0)
  await page.getByLabel('Первый день', { exact: true }).fill('2026-10-01')
  await expect(page.getByTestId('rent-total')).toHaveText(formatMoney(many.priceKopecks + another.priceKopecks))
  await expect(page.getByTestId('deposit-total')).toHaveText(formatMoney(many.depositKopecks + another.depositKopecks))
  await page.getByLabel(`Количество: ${many.title}`, { exact: true }).fill('2')
  await expect(page.getByTestId('rent-total')).toHaveText(formatMoney(many.priceKopecks * 2 + another.priceKopecks))
  const deposit = many.depositKopecks * 2 + another.depositKopecks
  await expect(page.getByTestId('deposit-total')).toHaveText(deposit ? formatMoney(deposit) : 'Без залога')
  await page.getByLabel('Последний день', { exact: true }).fill('2026-10-03')
  await expect(page.getByTestId('rent-total')).toHaveText(formatMoney((many.priceKopecks * 2 + another.priceKopecks) * 3))
  await expect(page.getByTestId('deposit-total')).toHaveText(deposit ? formatMoney(deposit) : 'Без залога')
  await page.getByLabel(`Количество: ${many.title}`, { exact: true }).fill(String(many.quantity + 1))
  await expect(page.getByRole('alert')).toContainText(`Доступно только ${many.quantity}`)
  await expect(page.getByLabel(`Количество: ${many.title}`, { exact: true })).toHaveValue('2')
  await page.getByRole('button', { name: 'Выбрать профиль и продолжить', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Войти как демо-участник', exact: true }).click()
  await expect(page.getByLabel('Текущий демо-участник', { exact: true })).toHaveValue('participant')
  await expect(page.getByTestId('selection-line')).toHaveCount(2)
  const state = await readBrowserState(page)
  expect(state.selections.find(item => item.actorId === 'participant')?.lines).toEqual([{ listingId: many.id, quantity: 2 }, { listingId: another.id, quantity: 1 }])
  expect(state.selections.some(item => item.actorId === 'guest')).toBe(false)
  await switchActor(page, many.ownerId)
  await open(page, `/items/${many.slug}`)
  await expect(page.getByRole('button', { name: 'Добавить в подборку', exact: true })).toBeDisabled()
  await expect(page.getByText('Это ваша вещь. Для запроса выберите другого демо-участника.', { exact: true })).toBeVisible()
})

test('темы и профиль владельца открывают только связанные опубликованные вещи; неизвестный адрес понятен', async ({ page }) => {
  for (const collection of seed.collections) {
    await open(page, `/collections/${collection.slug}`)
    await expect(page.getByRole('heading', { name: collection.title, exact: true })).toBeVisible()
    const ids = await page.getByTestId('listing-card').evaluateAll(cards => cards.map(card => card.getAttribute('data-id')))
    expect(ids.sort()).toEqual(published.filter(item => collection.listingIds.includes(item.id)).map(item => item.id).sort())
  }
  await open(page, `/owners/${first.ownerId}`)
  const ids = await page.getByTestId('listing-card').evaluateAll(cards => cards.map(card => card.getAttribute('data-id')))
  expect(ids.sort()).toEqual(published.filter(item => item.ownerId === first.ownerId).map(item => item.id).sort())
  await open(page, '/no-such-screen')
  await expect(page.getByRole('heading', { name: 'Этот кадр не найден', exact: true })).toBeVisible()
})

test('запрос атомарно делится по владельцам, повтор не дублирует; ответы, архив, история и завершение', async ({ page }) => {
  const one = first
  const two = published.find(item => item.ownerId !== one.ownerId)!
  await open(page)
  await switchActor(page, 'participant')
  await addItem(page, one)
  await addItem(page, two)
  await open(page, '/selection')
  await page.getByLabel('Первый день', { exact: true }).fill('2026-10-01')
  await page.getByLabel('Последний день', { exact: true }).fill('2026-10-03')
  await page.getByRole('button', { name: 'Отправить демо-запрос', exact: true }).click({ clickCount: 2 })
  await expect(page.getByRole('status')).toContainText('Демо-запрос сохранён')
  await expect(page.getByTestId('request-group')).toHaveCount(1)
  let state = await readBrowserState(page)
  expect(state.requestGroups).toHaveLength(1)
  expect(state.ownerRequests).toHaveLength(2)
  expect(state.requestGroups[0]!.ownerRequestIds).toHaveLength(2)
  expect(state.requestGroups[0]!.days).toBe(3)
  expect(state.selections.find(item => item.actorId === 'participant')?.lines).toEqual([])
  await switchActor(page, one.ownerId)
  await open(page, '/account/incoming')
  await expect(page.getByTestId('owner-request')).toHaveCount(1)
  await expect(page.getByTestId('owner-request')).toContainText(one.title)
  await expect(page.getByTestId('owner-request')).not.toContainText(two.title)
  await page.getByLabel(`Комментарий к ${one.title}`, { exact: true }).fill('В демо можно выдать в согласованное время.')
  await page.getByRole('button', { name: 'Подтвердить строку', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).requestGroups[0]!.status).toBe('partial')
  await switchActor(page, two.ownerId)
  await open(page, '/account/incoming')
  await expect(page.getByTestId('owner-request')).toHaveCount(1)
  await expect(page.getByTestId('owner-request')).toContainText(two.title)
  await expect(page.getByTestId('owner-request')).not.toContainText(one.title)
  await page.getByLabel(`Комментарий к ${two.title}`, { exact: true }).fill('Для этой демонстрации предмет недоступен.')
  await page.getByRole('button', { name: 'Отклонить строку', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).ownerRequests.find(part => part.ownerId === two.ownerId)?.status).toBe('rejected')
  await switchActor(page, 'participant')
  await open(page, '/account/requests')
  await expect(page.getByTestId('request-group').locator(':scope > .row .badge')).toHaveText('Частично подтверждено')
  await expect(page.getByTestId('owner-request')).toHaveCount(2)
  state = await readBrowserState(page)
  const snapshots = state.ownerRequests.map(part => part.lines)
  await switchActor(page, one.ownerId)
  await open(page, '/account/listings')
  await page.getByTestId('managed-listing').filter({ has: page.getByRole('heading', { name: one.title, exact: true }) }).getByRole('button', { name: 'В архив', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).listings.find(item => item.id === one.id)?.status).toBe('archived')
  await switchActor(page, 'guest')
  await open(page, `/items/${one.slug}`)
  await expect(page.getByRole('heading', { name: 'Этот кадр не найден', exact: true })).toBeVisible()
  expect((await readBrowserState(page)).ownerRequests.map(part => part.lines)).toEqual(snapshots)
  await switchActor(page, 'participant')
  await open(page, '/account/requests')
  await expect(page.getByTestId('request-group')).toContainText(one.title)
  await page.getByRole('button', { name: 'Завершить демо-сценарий', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).requestGroups[0]!.status).toBe('completed')
  await page.getByRole('combobox', { name: 'Статус запросов', exact: true }).selectOption('completed')
  await expect(page.getByTestId('request-group')).toHaveCount(1)
})

test('арендатор отменяет открытый запрос, у владельца исчезает возможность ответа', async ({ page }) => {
  await open(page)
  await switchActor(page, 'participant')
  await addItem(page, first)
  await open(page, '/selection')
  await page.getByLabel('Первый день', { exact: true }).fill('2026-10-01')
  await page.getByLabel('Последний день', { exact: true }).fill('2026-10-01')
  await page.getByRole('button', { name: 'Отправить демо-запрос', exact: true }).click()
  await expect(page.getByTestId('request-group')).toHaveCount(1)
  await page.getByRole('button', { name: 'Отменить запрос', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).requestGroups[0]!.status).toBe('cancelled')
  await switchActor(page, first.ownerId)
  await open(page, '/account/incoming')
  await expect(page.getByTestId('owner-request')).toContainText('Отменено')
  await expect(page.getByRole('button', { name: 'Подтвердить строку', exact: true })).toHaveCount(0)
})

async function createUploadedListing(page: Page) {
  await open(page)
  await page.getByRole('button', { name: 'Тестовый профиль', exact: true }).click()
  const login = page.getByRole('dialog', { name: 'Войти в демо' })
  expect(await login.locator('option').allTextContents()).not.toContain('Администратор демо')
  await login.getByLabel('Новый тестовый псевдоним', { exact: true }).fill('Сценограф демо')
  await login.getByRole('combobox', { name: 'Что хотите сделать сначала?', exact: true }).selectOption('rent')
  await login.getByRole('button', { name: 'Создать тестовый профиль', exact: true }).click()
  await expect(page.getByLabel('Название предмета', { exact: true })).toBeVisible()
  const actorId = await page.getByLabel('Текущий демо-участник', { exact: true }).inputValue()
  expect((await readBrowserState(page)).users.find(user => user.id === actorId)?.isAdmin).toBe(false)
  const title = 'Кресло кинопроверки'
  await page.getByRole('button', { name: 'Далее', exact: true }).click()
  await expect(page.getByText('Укажите название от 3 символов', { exact: true })).toBeVisible()
  for (const [label, value] of [
    ['Название предмета', title], ['Описание предмета', 'Демонстрационное кресло с оливковой обивкой для проверки загрузки и модерации.'],
    ['Материал', 'Дерево и ткань'], ['Цвет', 'Оливковый'], ['Размеры с единицами', '70 × 75 × 82 см'],
    ['Эпоха или стиль', 'Ретро'], ['Состояние', 'Тестовое состояние'],
  ]) await page.getByRole('textbox', { name: new RegExp(`^${label}`) }).fill(value)
  await page.getByRole('button', { name: 'Далее', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Покажите предмет', exact: true })).toBeVisible()
  await page.getByLabel('Фотографии предмета', { exact: true }).setInputFiles({ name: 'unsafe.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>') })
  await expect(page.getByRole('alert')).toContainText('SVG и HTML не принимаются')
  await expect(page.locator('.upload-grid img')).toHaveCount(0)
  const sourceImage = seed.images.find(image => image.id === first.imageIds[0])!
  const buffer = readFileSync(`public/${sourceImage.path}`)
  await page.getByLabel('Фотографии предмета', { exact: true }).setInputFiles([
    { name: 'chair-one.webp', mimeType: 'image/webp', buffer },
    { name: 'chair-two.webp', mimeType: 'image/webp', buffer },
  ])
  await expect(page.locator('.upload-grid img')).toHaveCount(2)
  const oldOrder = (await readBrowserState(page)).images.slice(-2).map(image => image.id)
  await page.locator('.upload-grid').getByRole('button', { name: 'Главное', exact: true }).nth(1).click()
  await page.getByRole('button', { name: 'Сохранить черновик', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Черновик сохранён')
  let state = await readBrowserState(page)
  const item = state.listings.find(listing => listing.ownerId === actorId && listing.title === title)!
  expect(item.imageIds).toEqual([oldOrder[1], oldOrder[0]])
  expect(item.status).toBe('draft')
  expect(state.sellers.some(seller => seller.userId === actorId)).toBe(true)
  await page.reload()
  await expect(page.getByLabel('Название предмета', { exact: true })).toHaveValue(title)
  await page.getByRole('button', { name: 'Далее', exact: true }).click()
  await expect(page.locator('.upload-grid img')).toHaveCount(2)
  await expect.poll(() => page.locator('.upload-grid img').evaluateAll(images => (images as HTMLImageElement[]).every(image => image.complete && image.naturalWidth > 0))).toBe(true)
  state = await readBrowserState(page)
  for (const imageId of item.imageIds) expect(state.images.find(image => image.id === imageId)?.blob).toBeTruthy()
  await page.getByRole('button', { name: 'Далее', exact: true }).click()
  await page.getByLabel(/^Цена за день, ₽/).fill('1250')
  await page.getByLabel(/^Залог за единицу, ₽/).fill('2500')
  await page.getByLabel('Доступное количество', { exact: true }).fill('2')
  await page.getByLabel('Район', { exact: true }).fill('Москва · Хамовники')
  await page.getByRole('textbox', { name: 'Условия выдачи', exact: true }).fill('Демо-самовывоз после согласования времени.')
  await page.getByRole('textbox', { name: 'Упаковка', exact: true }).fill('Тестовый защитный чехол.')
  await page.setViewportSize({ width: 360, height: 800 })
  await assertNoOverflow(page)
  await page.getByRole('button', { name: 'Отправить на модерацию', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).listings.find(listing => listing.id === item.id)?.status).toBe('pending')
  return { actorId, itemId: item.id, slug: item.slug, title, imageIds: item.imageIds }
}

async function openModerationItem(page: Page, title: string) {
  await switchActor(page, 'admin')
  await open(page, '/admin/moderation')
  await page.locator('.listing-manage').filter({ has: page.getByRole('heading', { name: title, exact: true }) }).getByRole('button', { name: 'Проверить объявление', exact: true }).click()
  return page.getByRole('dialog', { name: 'Модерация объявления', exact: true })
}

test('новый профиль, безопасные фото, черновик reload, отклонение, исправление и публикация', async ({ page }) => {
  const { actorId, itemId, slug, title } = await createUploadedListing(page)
  await switchActor(page, 'guest')
  await open(page, `/items/${slug}`)
  await expect(page.getByRole('heading', { name: 'Этот кадр не найден', exact: true })).toBeVisible()
  let modal = await openModerationItem(page, title)
  await modal.getByRole('button', { name: 'Отклонить объявление', exact: true }).click()
  await expect(modal.getByRole('alert')).toContainText('Укажите причину отклонения')
  await modal.getByLabel('Причина отклонения', { exact: true }).fill('Уточните условия демонстрационной выдачи.')
  await modal.getByRole('button', { name: 'Отклонить объявление', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).listings.find(listing => listing.id === itemId)?.status).toBe('rejected')
  await switchActor(page, actorId)
  await open(page, `/listing/${itemId}/edit`)
  await expect(page.getByText('Причина отклонения: Уточните условия демонстрационной выдачи.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Далее', exact: true }).click()
  await page.getByRole('button', { name: 'Далее', exact: true }).click()
  await page.getByRole('textbox', { name: 'Условия выдачи', exact: true }).fill('Уточнённый демо-самовывоз: упаковка и время согласуются отдельно.')
  await page.getByRole('button', { name: 'Отправить на модерацию', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).listings.find(listing => listing.id === itemId)?.status).toBe('pending')
  modal = await openModerationItem(page, title)
  await modal.getByRole('button', { name: 'Опубликовать', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).listings.find(listing => listing.id === itemId)?.status).toBe('published')
  await switchActor(page, 'guest')
  await open(page, `/items/${slug}`)
  await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible()
  await assertVisibleImages(page)
  await switchActor(page, 'participant')
  await open(page, `/listing/${itemId}/edit`)
  await expect(page.getByRole('heading', { name: 'Это чужое объявление', exact: true })).toBeVisible()
  await switchActor(page, actorId)
  await open(page, `/listing/${itemId}/edit`)
  await page.getByLabel('Название предмета', { exact: true }).fill(`${title} после правки`)
  await page.getByRole('button', { name: 'Сохранить черновик', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).listings.find(listing => listing.id === itemId)?.status).toBe('pending')
  await switchActor(page, 'guest')
  await open(page, `/items/${slug}`)
  await expect(page.getByRole('heading', { name: 'Этот кадр не найден', exact: true })).toBeVisible()
})

test('ZIP содержит реальные загруженные фото; проверка, сброс и импорт сохраняют карточку без приватных данных', async ({ page }, testInfo) => {
  test.setTimeout(120000)
  const created = await createUploadedListing(page)
  const modal = await openModerationItem(page, created.title)
  await modal.getByRole('button', { name: 'Опубликовать', exact: true }).click()
  await switchActor(page, 'participant')
  const local = (await readBrowserState(page)).listings.find(item => item.id === created.itemId)!
  await addItem(page, local)
  await open(page, '/selection')
  await page.getByLabel('Первый день', { exact: true }).fill('2026-10-01')
  await page.getByLabel('Последний день', { exact: true }).fill('2026-10-01')
  await page.getByRole('button', { name: 'Ссылка для другого устройства', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('В подборке есть локальная карточка')
  await page.getByRole('button', { name: 'Отправить демо-запрос', exact: true }).click()
  await expect(page.getByTestId('request-group')).toHaveCount(1)
  await switchActor(page, 'admin')
  await open(page, '/admin/data')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Экспорт ZIP с фото', exact: true }).click()
  const download = await downloadPromise
  const archivePath = testInfo.outputPath('kinostore-roundtrip.zip')
  await download.saveAs(archivePath)
  const files = unzipSync(new Uint8Array(readFileSync(archivePath)))
  const exported = JSON.parse(strFromU8(files['catalog.json']!)) as CatalogPackage
  expect(Object.keys(exported).sort()).toEqual(['categories', 'collections', 'images', 'listings', 'schemaVersion', 'sellers'])
  expect(exported.listings.find(item => item.id === created.itemId)?.title).toBe(created.title)
  expect(JSON.stringify(exported)).not.toContain('blob:')
  for (const imageId of created.imageIds) {
    const image = exported.images.find(asset => asset.id === imageId)!
    expect(files[image.path]!.byteLength).toBeGreaterThan(100)
  }
  const before = await readBrowserState(page)
  const malicious = zipSync({ '../outside.txt': strToU8('must never be written'), 'catalog.json': strToU8(JSON.stringify(exported)) })
  await page.getByLabel('Пакет каталога ZIP', { exact: true }).setInputFiles({ name: 'unsafe.zip', mimeType: 'application/zip', buffer: Buffer.from(malicious) })
  await expect(page.getByRole('alert')).toContainText('Недопустимый путь')
  await expect(page.getByRole('button', { name: 'Применить импорт', exact: true })).toHaveCount(0)
  let after = await readBrowserState(page)
  expect(after.revision).toBe(before.revision)
  expect(after.listings).toEqual(before.listings)
  expect(after.requestGroups).toEqual(before.requestGroups)
  await page.getByRole('button', { name: 'Восстановить демонстрационные данные', exact: true }).click()
  const reset = page.getByRole('dialog', { name: 'Сбросить локальное демо?', exact: true })
  await expect(reset.getByRole('button', { name: 'Сначала экспортировать каталог', exact: true })).toBeVisible()
  await expect(reset.getByRole('button', { name: 'Подтвердить сброс', exact: true })).toBeDisabled()
  await reset.getByLabel('Введите СБРОСИТЬ', { exact: true }).fill('СБРОСИТЬ')
  await reset.getByRole('button', { name: 'Подтвердить сброс', exact: true }).click()
  await expect(reset).toHaveCount(0)
  after = await readBrowserState(page)
  expect(after.listings.some(item => item.id === created.itemId)).toBe(false)
  expect(after.requestGroups).toEqual([])
  await page.getByLabel('Пакет каталога ZIP', { exact: true }).setInputFiles(archivePath)
  await expect(page.getByRole('status').filter({ hasText: 'Режим: добавление и обновление по ID' })).toBeVisible()
  await page.getByRole('button', { name: 'Применить импорт', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).listings.some(item => item.id === created.itemId)).toBe(true)
  after = await readBrowserState(page)
  expect(after.listings.find(item => item.id === created.itemId)?.imageIds).toEqual(created.imageIds)
  expect(after.requestGroups).toEqual([])
  expect(after.users.filter(user => user.isAdmin).map(user => user.id)).toEqual(['admin'])
  for (const id of created.imageIds) expect(after.images.find(image => image.id === id)?.blob).toBeTruthy()
  await page.reload()
  await switchActor(page, 'guest')
  await open(page, `/items/${created.slug}`)
  await expect(page.getByRole('heading', { name: created.title, exact: true })).toBeVisible()
  await assertVisibleImages(page)
})

test('администратор меняет порядок категорий, удаление занятой категории запрещено, журнал и счётчики фактические', async ({ page }) => {
  await open(page)
  await switchActor(page, 'participant')
  await open(page, '/admin/data')
  await expect(page.getByRole('button', { name: 'Экспорт ZIP с фото', exact: true })).toHaveCount(0)
  await switchActor(page, 'admin')
  await open(page, '/admin/categories')
  await page.getByRole('button', { name: 'Удалить', exact: true }).first().click()
  await expect(page.getByRole('alert')).toContainText('Нельзя удалить категорию с объявлениями')
  expect((await readBrowserState(page)).categories).toHaveLength(8)
  await page.getByRole('button', { name: 'Изменить', exact: true }).first().click()
  const modal = page.getByRole('dialog', { name: 'Редактировать категорию', exact: true })
  await modal.getByLabel('Название категории', { exact: true }).fill('Мебель для кадра')
  await modal.getByLabel('Порядок категории', { exact: true }).fill('50')
  await modal.getByRole('button', { name: 'Сохранить категорию', exact: true }).click()
  await open(page)
  const categories = page.getByRole('navigation', { name: 'Категории' }).getByRole('link')
  await expect(categories.last()).toContainText('Мебель для кадра')
  await open(page, '/admin/overview')
  await expect(page.getByRole('cell', { name: 'Обновлена категория', exact: true })).toBeVisible()
  const state = await readBrowserState(page)
  await expect(page.locator('.metric').filter({ hasText: 'Опубликовано' }).locator('strong')).toHaveText(String(state.listings.filter(item => item.status === 'published').length))
  await expect(page.locator('.metric').filter({ hasText: 'Владельцев' }).locator('strong')).toHaveText(String(state.sellers.length))
  await expect(page.locator('.metric').filter({ hasText: 'Запросов' }).locator('strong')).toHaveText(String(state.requestGroups.length))
})

test('сохранённая подборка переживает reload, изолирована по участнику; текст и исходная ссылка переносимы', async ({ page, context, browser }) => {
  const item = published.find(listing => listing.quantity >= 2)!
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await open(page)
  await switchActor(page, 'participant')
  await addItem(page, item, 2)
  await open(page, '/selection')
  await page.getByLabel('Первый день', { exact: true }).fill('2026-10-01')
  await page.getByLabel('Последний день', { exact: true }).fill('2026-10-03')
  await page.getByLabel('Название подборки', { exact: true }).fill('Сцена для проверки')
  await page.getByRole('button', { name: 'Сохранить подборку', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).savedSelections.length).toBe(1)
  await page.getByRole('button', { name: 'Копировать текст', exact: true }).click()
  const copied = await page.evaluate(() => navigator.clipboard.readText())
  expect(copied).toContain(item.title)
  expect(copied).toContain('Итого аренда: ' + formatMoney(item.priceKopecks * 2 * 3))
  await page.getByRole('button', { name: 'Ссылка для другого устройства', exact: true }).click()
  const sharedUrl = await page.evaluate(() => navigator.clipboard.readText())
  expect(sharedUrl.length).toBeLessThanOrEqual(4000)
  const payload = JSON.parse(new URLSearchParams(new URL(sharedUrl).hash.split('?')[1]).get('data')!)
  expect(payload).toEqual({ v: 1, start: '2026-10-01', end: '2026-10-03', items: [{ id: item.id, q: 2 }] })
  const fresh = await browser.newContext()
  try {
    const phone = await fresh.newPage()
    await phone.setViewportSize({ width: 390, height: 844 })
    await phone.goto(sharedUrl)
    await phone.getByRole('button', { name: 'Добавить в мою подборку', exact: true }).click()
    await expect(phone.getByTestId('selection-line')).toHaveCount(1)
    expect((await readBrowserState(phone)).selections.find(selection => selection.actorId === 'guest')).toMatchObject({ startDate: '2026-10-01', endDate: '2026-10-03', lines: [{ listingId: item.id, quantity: 2 }] })
    const badUrl = new URL(sharedUrl)
    badUrl.hash = '/share?data=' + encodeURIComponent(JSON.stringify({ ...payload, contacts: 'forbidden extra field' }))
    await phone.goto(badUrl.href)
    await expect(phone.getByRole('heading', { name: 'Некорректная ссылка подборки', exact: true })).toBeVisible()
    expect((await readBrowserState(phone)).selections.find(selection => selection.actorId === 'guest')?.lines).toEqual([{ listingId: item.id, quantity: 2 }])
  } finally { await fresh.close() }
  await page.reload()
  await page.getByRole('button', { name: `Удалить: ${item.title}`, exact: true }).click()
  await open(page, '/account/selections')
  await expect(page.getByRole('heading', { name: 'Сцена для проверки', exact: true })).toBeVisible()
  await switchActor(page, item.ownerId)
  await expect(page.getByRole('heading', { name: 'Сцена для проверки', exact: true })).toHaveCount(0)
  await switchActor(page, 'participant')
  await page.getByRole('button', { name: 'Открыть подборку', exact: true }).click()
  await expect(page.getByTestId('selection-line')).toHaveCount(1)
  await expect(page.getByLabel(`Количество: ${item.title}`, { exact: true })).toHaveValue('2')
  await expect(page.getByLabel('Первый день', { exact: true })).toHaveValue('2026-10-01')
  await expect(page.getByLabel('Последний день', { exact: true })).toHaveValue('2026-10-03')
  await open(page, '/account/selections')
  await page.getByRole('button', { name: 'Удалить подборку', exact: true }).click()
  await expect.poll(async () => (await readBrowserState(page)).savedSelections.length).toBe(0)
})
